name: Bug report
description: Create a report describing unexpected or incorrect behavior in astropy.
labels: Bug
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the [Astropy Code of Conduct](https://github.com/astropy/astropy/blob/main/CODE_OF_CONDUCT.md).
          required: true
  - type: checkboxes
    attributes:
      label: Contributing guidelines
      options:
        - label: >-
            I have read the [Astropy Contributing Guidelines](https://github.com/astropy/astropy/blob/main/CONTRIBUTING.md).
  - type: checkboxes
    attributes:
      label: Check for existing issue
      options:
        - label: >-
            I found no existing issues already reported of the same problem on [astropy GitHub issues](https://github.com/astropy/astropy/issues).
  - type: checkboxes
    attributes:
      label: Bug still in dev
      options:
        - label: >-
            I checked that this bug still occurs in the dev version of astropy.
  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Actual behavior
      description: >-
        A clear and concise description of what actually happened instead.
        Was the output confusing or poorly described?
  - type: textarea
    attributes:
      label: How to Reproduce
      description: Please provide steps to reproduce this bug.
      placeholder: |
        1. Get package from '...'
        2. Then run '...'
        3. An error occurs.
    validations:
      required: true
  - type: input
    attributes:
      label: astropy version
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
    validations:
      required: true
  - type: input
    attributes:
      label: OS
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other relevant versions
      description: Version of other relevant packages.
      placeholder: |
        import numpy; print("Numpy", numpy.__version__)
        import erfa; print("pyerfa", erfa.__version__)
        import scipy; print("Scipy", scipy.__version__)
        import matplotlib; print("Matplotlib", matplotlib.__version__)
