name: Feature request
description: Suggest an idea to improve astropy.
labels: "Feature Request"
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the [Astropy Code of Conduct](https://github.com/astropy/astropy/blob/main/CODE_OF_CONDUCT.md).
          required: true
  - type: checkboxes
    attributes:
      label: Contributing guidelines
      options:
        - label: >-
            I have read the [Astropy Contributing Guidelines](https://github.com/astropy/astropy/blob/main/CONTRIBUTING.md).
  - type: checkboxes
    attributes:
      label: Check for existing issue
      options:
        - label: >-
            I found no existing issues already reported of the same request on [astropy GitHub issues](https://github.com/astropy/astropy/issues).
  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
      description: >-
        What are you trying to do, that you are unable to achieve with astropy
        and its affiliated packages as it currently stands?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the desired outcome
      description: >-
        Clear and concise description of what you want to happen. Please use examples
        of real world use cases that this would help with, and how it solves the
        problem described above. If you want to, you can suggest a draft design or API
        so we can have a deeper discussion on the feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context, links, etc. relevant to the feature request.
        You may also include screenshots if necessary.
